
import 'package:flutter/widgets.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
/// This code is autogenerated in the backend repo in extract-i18n.py do not edit!

/// Translate dynamic strings that are returned from the server
/// These strings such as categories or equipment are returned by the server
/// in English and need to be translated here in the application (there are
/// probably better ways to do this, but that's the way it is right now).

String getTranslation(String value, BuildContext context) {
  switch (value) {
    case 'Until Failure':
      return AppLocalizations.of(context).until_failure;

    case 'Calves':
      return AppLocalizations.of(context).calves;

    case 'Dumbbell':
      return AppLocalizations.of(context).dumbbell;

    case 'Barbell':
      return AppLocalizations.of(context).barbell;

    case 'Swiss Ball':
      return AppLocalizations.of(context).swiss_ball;

    case 'Gym mat':
      return AppLocalizations.of(context).gym_mat;

    case 'Miles':
      return AppLocalizations.of(context).miles;

    case 'Minutes':
      return AppLocalizations.of(context).minutes;

    case 'Chest':
      return AppLocalizations.of(context).chest;

    case 'Kilometers':
      return AppLocalizations.of(context).kilometers;

    case 'Shoulders':
      return AppLocalizations.of(context).shoulders;

    case 'Cardio':
      return AppLocalizations.of(context).cardio;

    case 'Biceps':
      return AppLocalizations.of(context).biceps;

    case 'Arms':
      return AppLocalizations.of(context).arms;

    case 'Triceps':
      return AppLocalizations.of(context).triceps;

    case 'Glutes':
      return AppLocalizations.of(context).glutes;

    case 'Legs':
      return AppLocalizations.of(context).legs;

    case 'Repetitions':
      return AppLocalizations.of(context).repetitions;

    case 'Seconds':
      return AppLocalizations.of(context).seconds;

    case 'Quads':
      return AppLocalizations.of(context).quads;

    case 'SZ-Bar':
      return AppLocalizations.of(context).sz_bar;

    case 'Back':
      return AppLocalizations.of(context).back;

    case 'Bench':
      return AppLocalizations.of(context).bench;

    case 'Lats':
      return AppLocalizations.of(context).lats;

    case 'Incline bench':
      return AppLocalizations.of(context).incline_bench;

    case 'Pull-up bar':
      return AppLocalizations.of(context).pull_up_bar;

    case 'Abs':
      return AppLocalizations.of(context).abs;

    case 'Hamstrings':
      return AppLocalizations.of(context).hamstrings;

    case 'none (bodyweight exercise)':
      return AppLocalizations.of(context).none__bodyweight_exercise_;

    case 'Lower back':
      return AppLocalizations.of(context).lower_back;

    case 'Kettlebell':
      return AppLocalizations.of(context).kettlebell;
    default:
      return 'NOT TRANSLATED';
  }}
}}