import 'package:json_annotation/json_annotation.dart';
import 'package:wger/models/exercises/exercise.dart';
import 'package:wger/models/workouts//weight_unit.dart';
import 'package:wger/models/workouts/repetition_unit.dart';

part 'setting.g.dart';

@JsonSerializable()
class Setting {
  @JsonKey(required: true)
  final int id;

  @JsonKey(required: true)
  Exercise exercise;

  @JsonKey(required: true, name: 'repetition_unit')
  RepetitionUnit repetitionUnit;

  @JsonKey(required: true)
  int reps;

  @JsonKey(required: true)
  double weight;

  @JsonKey(required: true, name: 'weight_unit')
  WeightUnit weightUnit;

  @JsonKey(required: true)
  String comment;

  // Generated by Server
  @JsonKey(required: true)
  String repsText;

  Setting({
    this.id,
    this.exercise,
    this.repetitionUnit,
    this.reps,
    this.weight,
    this.weightUnit,
    this.comment,
    this.repsText,
  });

  // Boilerplate
  factory Setting.fromJson(Map<String, dynamic> json) => _$SettingFromJson(json);
  Map<String, dynamic> toJson() => _$SettingToJson(this);
}
