// Mocks generated by Mockito 5.4.6 from annotations
// in wger/test/exercises/contribute_exercise_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wger/models/core/language.dart' as _i15;
import 'package:wger/models/core/search_options.dart' as _i9;
import 'package:wger/models/exercises/category.dart' as _i11;
import 'package:wger/models/exercises/equipment.dart' as _i13;
import 'package:wger/models/exercises/exercise_filters.dart' as _i10;
import 'package:wger/models/exercises/exercise_submission.dart' as _i5;
import 'package:wger/models/exercises/exercise_submission_images.dart' as _i6;
import 'package:wger/models/exercises/muscle.dart' as _i14;
import 'package:wger/models/user/profile.dart' as _i2;
import 'package:wger/providers/add_exercise_repository.dart' as _i3;
import 'package:wger/providers/exercise_repository.dart' as _i8;
import 'package:wger/providers/exercises_notifier.dart' as _i12;
import 'package:wger/providers/user_profile_repository.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfile_0 extends _i1.SmartFake implements _i2.Profile {
  _FakeProfile_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [AddExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddExerciseRepository extends _i1.Mock implements _i3.AddExerciseRepository {
  MockAddExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> submit(_i5.ExerciseSubmissionApi? payload) =>
      (super.noSuchMethod(
            Invocation.method(#submit, [payload]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> uploadImage({
    required int? exerciseId,
    required _i6.ExerciseSubmissionImage? image,
    required String? author,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [], {
              #exerciseId: exerciseId,
              #image: image,
              #author: author,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepository extends _i1.Mock implements _i7.UserProfileRepository {
  MockUserProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Profile> fetchProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, []),
            returnValue: _i4.Future<_i2.Profile>.value(
              _FakeProfile_0(this, Invocation.method(#fetchProfile, [])),
            ),
          )
          as _i4.Future<_i2.Profile>);

  @override
  _i4.Future<void> saveProfile(_i2.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [profile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> verifyEmail() =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock implements _i8.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<int>> searchExerciseServer(
    String? term, {
    String? languageCode = 'en',
    bool? searchEnglish = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchExerciseServer,
              [term],
              {#languageCode: languageCode, #searchEnglish: searchEnglish},
            ),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<List<int>> searchExerciseServerWithSearchMode(
    String? term, {
    String? languageCode = 'en',
    _i9.SearchLanguage? searchLanguage = _i9.SearchLanguage.currentAndEnglish,
    _i10.ExerciseSearchMode? searchMode = _i10.ExerciseSearchMode.fulltext,
    Set<_i11.ExerciseCategory>? categories = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchExerciseServerWithSearchMode,
              [term],
              {
                #languageCode: languageCode,
                #searchLanguage: searchLanguage,
                #searchMode: searchMode,
                #categories: categories,
              },
            ),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Stream<_i12.ExerciseState> watchAllDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllDrift, []),
            returnValue: _i4.Stream<_i12.ExerciseState>.empty(),
          )
          as _i4.Stream<_i12.ExerciseState>);

  @override
  _i4.Stream<List<_i11.ExerciseCategory>> watchCategoriesDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchCategoriesDrift, []),
            returnValue: _i4.Stream<List<_i11.ExerciseCategory>>.empty(),
          )
          as _i4.Stream<List<_i11.ExerciseCategory>>);

  @override
  _i4.Stream<List<_i13.Equipment>> watchEquipmentDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchEquipmentDrift, []),
            returnValue: _i4.Stream<List<_i13.Equipment>>.empty(),
          )
          as _i4.Stream<List<_i13.Equipment>>);

  @override
  _i4.Stream<List<_i14.Muscle>> watchMusclesDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchMusclesDrift, []),
            returnValue: _i4.Stream<List<_i14.Muscle>>.empty(),
          )
          as _i4.Stream<List<_i14.Muscle>>);

  @override
  _i4.Stream<List<_i15.Language>> watchLanguagesDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchLanguagesDrift, []),
            returnValue: _i4.Stream<List<_i15.Language>>.empty(),
          )
          as _i4.Stream<List<_i15.Language>>);
}
