// Mocks generated by Mockito 5.4.6 from annotations
// in wger/test/exercises/contribute_exercise_image_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wger/models/exercises/exercise_submission.dart' as _i4;
import 'package:wger/models/exercises/exercise_submission_images.dart' as _i5;
import 'package:wger/providers/add_exercise_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AddExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddExerciseRepository extends _i1.Mock implements _i2.AddExerciseRepository {
  MockAddExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> submit(_i4.ExerciseSubmissionApi? payload) =>
      (super.noSuchMethod(
            Invocation.method(#submit, [payload]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> uploadImage({
    required int? exerciseId,
    required _i5.ExerciseSubmissionImage? image,
    required String? author,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [], {
              #exerciseId: exerciseId,
              #image: image,
              #author: author,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> validateLanguage(String? input, String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#validateLanguage, [input, languageCode]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
