// Mocks generated by Mockito 5.4.6 from annotations
// in wger/test/exercises/exercises_detail_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wger/models/core/language.dart' as _i10;
import 'package:wger/models/core/search_options.dart' as _i4;
import 'package:wger/models/exercises/category.dart' as _i6;
import 'package:wger/models/exercises/equipment.dart' as _i8;
import 'package:wger/models/exercises/exercise_filters.dart' as _i5;
import 'package:wger/models/exercises/muscle.dart' as _i9;
import 'package:wger/providers/exercise_repository.dart' as _i2;
import 'package:wger/providers/exercises_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock implements _i2.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<int>> searchExerciseServer(
    String? term, {
    String? languageCode = 'en',
    bool? searchEnglish = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchExerciseServer,
              [term],
              {#languageCode: languageCode, #searchEnglish: searchEnglish},
            ),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<List<int>> searchExerciseServerWithSearchMode(
    String? term, {
    String? languageCode = 'en',
    _i4.SearchLanguage? searchLanguage = _i4.SearchLanguage.currentAndEnglish,
    _i5.ExerciseSearchMode? searchMode = _i5.ExerciseSearchMode.fulltext,
    Set<_i6.ExerciseCategory>? categories = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchExerciseServerWithSearchMode,
              [term],
              {
                #languageCode: languageCode,
                #searchLanguage: searchLanguage,
                #searchMode: searchMode,
                #categories: categories,
              },
            ),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Stream<_i7.ExerciseState> watchAllDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllDrift, []),
            returnValue: _i3.Stream<_i7.ExerciseState>.empty(),
          )
          as _i3.Stream<_i7.ExerciseState>);

  @override
  _i3.Stream<List<_i6.ExerciseCategory>> watchCategoriesDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchCategoriesDrift, []),
            returnValue: _i3.Stream<List<_i6.ExerciseCategory>>.empty(),
          )
          as _i3.Stream<List<_i6.ExerciseCategory>>);

  @override
  _i3.Stream<List<_i8.Equipment>> watchEquipmentDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchEquipmentDrift, []),
            returnValue: _i3.Stream<List<_i8.Equipment>>.empty(),
          )
          as _i3.Stream<List<_i8.Equipment>>);

  @override
  _i3.Stream<List<_i9.Muscle>> watchMusclesDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchMusclesDrift, []),
            returnValue: _i3.Stream<List<_i9.Muscle>>.empty(),
          )
          as _i3.Stream<List<_i9.Muscle>>);

  @override
  _i3.Stream<List<_i10.Language>> watchLanguagesDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchLanguagesDrift, []),
            returnValue: _i3.Stream<List<_i10.Language>>.empty(),
          )
          as _i3.Stream<List<_i10.Language>>);
}
