// Mocks generated by Mockito 5.4.6 from annotations
// in wger/test/nutrition/nutritional_plan_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wger/models/nutrition/ingredient.dart' as _i6;
import 'package:wger/models/nutrition/nutritional_plan.dart' as _i5;
import 'package:wger/providers/ingredient_repository.dart' as _i7;
import 'package:wger/providers/nutrition_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [NutritionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionRepository extends _i1.Mock implements _i3.NutritionRepository {
  MockNutritionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<dynamic>> fetchAllPlans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllPlans, []),
            returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> fetchPlanSparse(int? planId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlanSparse, [planId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> fetchPlanFull(int? planId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlanFull, [planId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createPlan(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createPlan, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> updatePlan(int? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlan, [id, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Response> deletePlan(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlan, [id]),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#deletePlan, [id])),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Stream<List<_i5.NutritionalPlan>> watchAllDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllDrift, []),
            returnValue: _i4.Stream<List<_i5.NutritionalPlan>>.empty(),
          )
          as _i4.Stream<List<_i5.NutritionalPlan>>);

  @override
  _i4.Future<void> editLocalDrift(_i5.NutritionalPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#editLocalDrift, [plan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLocalDrift(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalDrift, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> createMeal(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createMeal, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateMeal(
    int? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMeal, [id, data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.Response> deleteMeal(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeal, [id]),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#deleteMeal, [id])),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<Map<String, dynamic>> createMealItem(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createMealItem, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.Response> deleteMealItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMealItem, [id]),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#deleteMealItem, [id])),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<List<_i6.Ingredient>> searchIngredient(
    String? name, {
    String? languageCode = 'en',
    _i3.IngredientSearchLanguage? searchLanguage = _i3.IngredientSearchLanguage.current,
    bool? isVegan = false,
    bool? isVegetarian = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchIngredient,
              [name],
              {
                #languageCode: languageCode,
                #searchLanguage: searchLanguage,
                #isVegan: isVegan,
                #isVegetarian: isVegetarian,
              },
            ),
            returnValue: _i4.Future<List<_i6.Ingredient>>.value(
              <_i6.Ingredient>[],
            ),
          )
          as _i4.Future<List<_i6.Ingredient>>);

  @override
  _i4.Future<_i6.Ingredient?> searchIngredientWithBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#searchIngredientWithBarcode, [barcode]),
            returnValue: _i4.Future<_i6.Ingredient?>.value(),
          )
          as _i4.Future<_i6.Ingredient?>);

  @override
  _i4.Future<List<dynamic>> fetchLogsForPlan(int? planId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLogsForPlan, [planId]),
            returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createLog(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createLog, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.Response> deleteLog(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLog, [id]),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#deleteLog, [id])),
            ),
          )
          as _i4.Future<_i2.Response>);
}

/// A class which mocks [IngredientRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientRepository extends _i1.Mock implements _i7.IngredientRepository {
  MockIngredientRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.Ingredient?> watchById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchById, [id]),
            returnValue: _i4.Stream<_i6.Ingredient?>.empty(),
          )
          as _i4.Stream<_i6.Ingredient?>);

  @override
  _i4.Future<_i6.Ingredient?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i6.Ingredient?>.value(),
          )
          as _i4.Future<_i6.Ingredient?>);
}
