// Mocks generated by Mockito 5.4.6 from annotations
// in wger/test/nutrition/nutritional_plans_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i12;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:wger/models/body_weight/weight_entry.dart' as _i14;
import 'package:wger/models/nutrition/ingredient.dart' as _i7;
import 'package:wger/models/nutrition/log.dart' as _i8;
import 'package:wger/models/nutrition/nutritional_plan.dart' as _i6;
import 'package:wger/models/user/profile.dart' as _i3;
import 'package:wger/providers/body_weight_repository.dart' as _i13;
import 'package:wger/providers/ingredient_repository.dart' as _i9;
import 'package:wger/providers/nutrition_repository.dart' as _i4;
import 'package:wger/providers/user_profile_repository.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeStreamedResponse_1 extends _i1.SmartFake implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_2 extends _i1.SmartFake implements _i3.Profile {
  _FakeProfile_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [NutritionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionRepository extends _i1.Mock implements _i4.NutritionRepository {
  MockNutritionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<dynamic>> fetchAllPlans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllPlans, []),
            returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> fetchPlanSparse(int? planId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlanSparse, [planId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> fetchPlanFull(int? planId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlanFull, [planId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> createPlan(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createPlan, [data]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> updatePlan(int? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlan, [id, data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Response> deletePlan(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlan, [id]),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#deletePlan, [id])),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Stream<List<_i6.NutritionalPlan>> watchAllDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllDrift, []),
            returnValue: _i5.Stream<List<_i6.NutritionalPlan>>.empty(),
          )
          as _i5.Stream<List<_i6.NutritionalPlan>>);

  @override
  _i5.Future<void> editLocalDrift(_i6.NutritionalPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#editLocalDrift, [plan]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteLocalDrift(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalDrift, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> createMeal(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createMeal, [data]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> updateMeal(
    int? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMeal, [id, data]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.Response> deleteMeal(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeal, [id]),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#deleteMeal, [id])),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<Map<String, dynamic>> createMealItem(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createMealItem, [data]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.Response> deleteMealItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMealItem, [id]),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#deleteMealItem, [id])),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<List<_i7.Ingredient>> searchIngredient(
    String? name, {
    String? languageCode = 'en',
    _i4.IngredientSearchLanguage? searchLanguage = _i4.IngredientSearchLanguage.current,
    bool? isVegan = false,
    bool? isVegetarian = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchIngredient,
              [name],
              {
                #languageCode: languageCode,
                #searchLanguage: searchLanguage,
                #isVegan: isVegan,
                #isVegetarian: isVegetarian,
              },
            ),
            returnValue: _i5.Future<List<_i7.Ingredient>>.value(
              <_i7.Ingredient>[],
            ),
          )
          as _i5.Future<List<_i7.Ingredient>>);

  @override
  _i5.Future<_i7.Ingredient?> searchIngredientWithBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#searchIngredientWithBarcode, [barcode]),
            returnValue: _i5.Future<_i7.Ingredient?>.value(),
          )
          as _i5.Future<_i7.Ingredient?>);

  @override
  _i5.Stream<List<_i8.LogItem>> watchAllLogsHydrated() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllLogsHydrated, []),
            returnValue: _i5.Stream<List<_i8.LogItem>>.empty(),
          )
          as _i5.Stream<List<_i8.LogItem>>);

  @override
  _i5.Future<void> addLogLocalDrift(_i8.LogItem? log) =>
      (super.noSuchMethod(
            Invocation.method(#addLogLocalDrift, [log]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteLogLocalDrift(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLogLocalDrift, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [IngredientRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientRepository extends _i1.Mock implements _i9.IngredientRepository {
  MockIngredientRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i7.Ingredient?> watchById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchById, [id]),
            returnValue: _i5.Stream<_i7.Ingredient?>.empty(),
          )
          as _i5.Stream<_i7.Ingredient?>);

  @override
  _i5.Future<_i7.Ingredient?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i7.Ingredient?>.value(),
          )
          as _i5.Future<_i7.Ingredient?>);

  @override
  _i5.Future<List<_i7.Ingredient>> searchByName(
    String? term, {
    bool? isVegan = false,
    bool? isVegetarian = false,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchByName,
              [term],
              {#isVegan: isVegan, #isVegetarian: isVegetarian, #limit: limit},
            ),
            returnValue: _i5.Future<List<_i7.Ingredient>>.value(
              <_i7.Ingredient>[],
            ),
          )
          as _i5.Future<List<_i7.Ingredient>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i12.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i5.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i5.Future<_i12.Uint8List>);

  @override
  _i5.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i5.Future<_i2.StreamedResponse>.value(
              _FakeStreamedResponse_1(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BodyWeightRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBodyWeightRepository extends _i1.Mock implements _i13.BodyWeightRepository {
  MockBodyWeightRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i14.WeightEntry>> watchAllDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllDrift, []),
            returnValue: _i5.Stream<List<_i14.WeightEntry>>.empty(),
          )
          as _i5.Stream<List<_i14.WeightEntry>>);

  @override
  _i5.Future<void> deleteLocalDrift(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalDrift, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateLocalDrift(_i14.WeightEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocalDrift, [entry]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addLocalDrift(_i14.WeightEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#addLocalDrift, [entry]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepository extends _i1.Mock implements _i15.UserProfileRepository {
  MockUserProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Profile> fetchProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, []),
            returnValue: _i5.Future<_i3.Profile>.value(
              _FakeProfile_2(this, Invocation.method(#fetchProfile, [])),
            ),
          )
          as _i5.Future<_i3.Profile>);

  @override
  _i5.Future<void> saveProfile(_i3.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [profile]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> verifyEmail() =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
