// Mocks generated by Mockito 5.4.6 from annotations
// in wger/test/measurements/measurement_entries_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wger/models/core/search_options.dart' as _i13;
import 'package:wger/models/measurements/measurement_category.dart' as _i4;
import 'package:wger/models/measurements/measurement_entry.dart' as _i5;
import 'package:wger/models/nutrition/ingredient.dart' as _i12;
import 'package:wger/models/nutrition/log.dart' as _i10;
import 'package:wger/models/nutrition/meal.dart' as _i8;
import 'package:wger/models/nutrition/meal_item.dart' as _i9;
import 'package:wger/models/nutrition/nutritional_plan.dart' as _i7;
import 'package:wger/providers/ingredient_repository.dart' as _i11;
import 'package:wger/providers/measurement_repository.dart' as _i2;
import 'package:wger/providers/nutrition_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MeasurementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeasurementRepository extends _i1.Mock implements _i2.MeasurementRepository {
  MockMeasurementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.MeasurementCategory>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i4.MeasurementCategory>>.empty(),
          )
          as _i3.Stream<List<_i4.MeasurementCategory>>);

  @override
  _i3.Stream<_i4.MeasurementCategory?> watchLocalDriftCategoryById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchLocalDriftCategoryById, [id]),
            returnValue: _i3.Stream<_i4.MeasurementCategory?>.empty(),
          )
          as _i3.Stream<_i4.MeasurementCategory?>);

  @override
  _i3.Future<void> deleteLocalDrift(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalDrift, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLocalDrift(_i5.MeasurementEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocalDrift, [entry]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addLocalDrift(_i5.MeasurementEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#addLocalDrift, [entry]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLocalDriftCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalDriftCategory, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLocalDriftCategory(
    _i4.MeasurementCategory? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocalDriftCategory, [category]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addLocalDriftCategory(_i4.MeasurementCategory? category) =>
      (super.noSuchMethod(
            Invocation.method(#addLocalDriftCategory, [category]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NutritionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionRepository extends _i1.Mock implements _i6.NutritionRepository {
  MockNutritionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i7.NutritionalPlan>> watchAllDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllDrift, []),
            returnValue: _i3.Stream<List<_i7.NutritionalPlan>>.empty(),
          )
          as _i3.Stream<List<_i7.NutritionalPlan>>);

  @override
  _i3.Future<void> addPlanLocalDrift(_i7.NutritionalPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#addPlanLocalDrift, [plan]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> editLocalDrift(_i7.NutritionalPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#editLocalDrift, [plan]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLocalDrift(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalDrift, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i8.Meal>> watchAllMealsHydrated() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllMealsHydrated, []),
            returnValue: _i3.Stream<List<_i8.Meal>>.empty(),
          )
          as _i3.Stream<List<_i8.Meal>>);

  @override
  _i3.Future<void> addMealLocalDrift(_i8.Meal? meal) =>
      (super.noSuchMethod(
            Invocation.method(#addMealLocalDrift, [meal]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> editMealLocalDrift(_i8.Meal? meal) =>
      (super.noSuchMethod(
            Invocation.method(#editMealLocalDrift, [meal]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMealLocalDrift(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMealLocalDrift, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addMealItemLocalDrift(_i9.MealItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addMealItemLocalDrift, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> editMealItemLocalDrift(_i9.MealItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#editMealItemLocalDrift, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMealItemLocalDrift(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMealItemLocalDrift, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i10.LogItem>> watchAllLogsHydrated() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllLogsHydrated, []),
            returnValue: _i3.Stream<List<_i10.LogItem>>.empty(),
          )
          as _i3.Stream<List<_i10.LogItem>>);

  @override
  _i3.Future<void> addLogLocalDrift(_i10.LogItem? log) =>
      (super.noSuchMethod(
            Invocation.method(#addLogLocalDrift, [log]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLogLocalDrift(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLogLocalDrift, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IngredientRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientRepository extends _i1.Mock implements _i11.IngredientRepository {
  MockIngredientRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i12.Ingredient?> watchById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchById, [id]),
            returnValue: _i3.Stream<_i12.Ingredient?>.empty(),
          )
          as _i3.Stream<_i12.Ingredient?>);

  @override
  _i3.Stream<List<_i12.Ingredient>> watchAllDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllDrift, []),
            returnValue: _i3.Stream<List<_i12.Ingredient>>.empty(),
          )
          as _i3.Stream<List<_i12.Ingredient>>);

  @override
  _i3.Future<_i12.Ingredient?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i12.Ingredient?>.value(),
          )
          as _i3.Future<_i12.Ingredient?>);

  @override
  _i3.Future<List<_i12.Ingredient>> searchIngredientLocal(
    String? term, {
    bool? isVegan = false,
    bool? isVegetarian = false,
    _i12.NutriScore? nutriscoreMax,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchIngredientLocal,
              [term],
              {
                #isVegan: isVegan,
                #isVegetarian: isVegetarian,
                #nutriscoreMax: nutriscoreMax,
                #limit: limit,
              },
            ),
            returnValue: _i3.Future<List<_i12.Ingredient>>.value(
              <_i12.Ingredient>[],
            ),
          )
          as _i3.Future<List<_i12.Ingredient>>);

  @override
  _i3.Future<List<_i12.Ingredient>> searchIngredientServer(
    String? name, {
    String? languageCode = 'en',
    _i13.SearchLanguage? searchLanguage = _i13.SearchLanguage.current,
    bool? isVegan = false,
    bool? isVegetarian = false,
    _i12.NutriScore? nutriscoreMax,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchIngredientServer,
              [name],
              {
                #languageCode: languageCode,
                #searchLanguage: searchLanguage,
                #isVegan: isVegan,
                #isVegetarian: isVegetarian,
                #nutriscoreMax: nutriscoreMax,
              },
            ),
            returnValue: _i3.Future<List<_i12.Ingredient>>.value(
              <_i12.Ingredient>[],
            ),
          )
          as _i3.Future<List<_i12.Ingredient>>);

  @override
  _i3.Future<List<_i12.Ingredient>> search(
    String? name, {
    required bool? isOnline,
    String? languageCode = 'en',
    _i13.SearchLanguage? searchLanguage = _i13.SearchLanguage.current,
    bool? isVegan = false,
    bool? isVegetarian = false,
    _i12.NutriScore? nutriscoreMax,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [name],
              {
                #isOnline: isOnline,
                #languageCode: languageCode,
                #searchLanguage: searchLanguage,
                #isVegan: isVegan,
                #isVegetarian: isVegetarian,
                #nutriscoreMax: nutriscoreMax,
              },
            ),
            returnValue: _i3.Future<List<_i12.Ingredient>>.value(
              <_i12.Ingredient>[],
            ),
          )
          as _i3.Future<List<_i12.Ingredient>>);

  @override
  _i3.Future<_i12.Ingredient?> searchIngredientByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#searchIngredientByBarcode, [barcode]),
            returnValue: _i3.Future<_i12.Ingredient?>.value(),
          )
          as _i3.Future<_i12.Ingredient?>);
}
