name: 'Flutter common setup'
description: 'Common steps needed to setup the application'

runs:
  using: "composite"
  steps:

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.35.7
        cache: true

    - name: Install Flutter dependencies
      run: flutter pub get
      shell: bash

    - name: Install Flutter dependencies
      run: |
        dart --version
        flutter --version
      shell: bash