// Mocks generated by Mockito 5.4.6 from annotations
// in wger/test/user/user_profile_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wger/models/user/user_profile.dart' as _i4;
import 'package:wger/providers/user_profile_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepository extends _i1.Mock implements _i2.UserProfileRepository {
  MockUserProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.UserProfile?> watchDrift() =>
      (super.noSuchMethod(
            Invocation.method(#watchDrift, []),
            returnValue: _i3.Stream<_i4.UserProfile?>.empty(),
          )
          as _i3.Stream<_i4.UserProfile?>);

  @override
  _i3.Future<void> editLocalDrift(_i4.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#editLocalDrift, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
