name: Build Windows
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch/Tag to build'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
jobs:
  # TODO: we currently upload the release folder as a ZIP, which works as a
  #       portable version. For a proper installer (e.g. via Inno Setup or MSIX),
  #       see: https://docs.flutter.dev/platform-integration/windows/building
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout application
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Common flutter setup
        uses: ./.github/actions/flutter-common

      - name: Build .exe
        run: flutter build windows --release

      - name: Package release
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath windows-x64.zip

      - uses: actions/upload-artifact@v7
        with:
          name: builds-windows
          path: windows-x64.zip