name: Continous Integration
on:
  push:
    paths:
      - '**.dart'
      - 'pubspec.yaml'
  pull_request:
    branches: [ master, ]
    paths:
      - '**.dart'
      - 'pubspec.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sqlite3-dev
        run: sudo apt install libsqlite3-dev

      - name: Common flutter setup
        uses: ./.github/actions/flutter-common

      - run: |
          dart --version
          flutter --version

      - name: Test app
        run: flutter test --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
